# Generated by Django 2.2 on 2020-07-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
